### ISSUE TITLE
The last minicap can not run on Android O

### ISSUE THREAD

**Issue by KilmerZhao** [openstf/minicap#82] opened 2017-07-18 09:02 UTC
Hi ,

After use NDK build the last minicap code. I push the file "minicap.so" and "minicap" to devices.

When i use command "adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 1080x1920@360x640/0", it happen error.

The error message is:
PID: 10209
INFO: Using projection 1080x1920@360x640/0
INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue
ERROR: (external/MY_minicap/src/minicap_26.cpp:281: errno: None) Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue
ERROR: (jni/minicap/minicap.cpp:383: errno: None) Unable to start minicap with current config
INFO: (external/MY_minicap/src/minicap_26.cpp:312) Destroying virtual display

My device is Nexus 5x, Android version is Android 8.0.0

Please tell me how to fix it.Thrank you very much.

**Comment by sorccu** [comment] 2017-07-18 09:04
You just have to wait. There are already other issues about this. Duplicate of #67.

**Closed by sorccu** 2017-07-18 09:04 UTC

**Comment by KilmerZhao** [comment] 2017-07-18 09:18
I logcat the message when execute the command.

The error message:

07-18 16:47:28.605 W/linker  (12460): Warning: "/data/local/tmp/minicap-develop" is not a directory (excluding from path)
07-18 16:47:28.608 F/libc    (12460): CANNOT LINK EXECUTABLE "/data/local/tmp/minicap-devel/minicap": library "minicap.so" not found
07-18 16:47:28.608 F/libc    (12460): Fatal signal 6 (SIGABRT), code -6 in tid 12460 (minicap)
07-18 16:47:28.686 W/crash_dump64(12463): type=1400 audit(0.0:370): avc: denied { search } for name="tmp" dev="dm-2" ino=752194 scontext=u:r:crash_dump:s0 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
07-18 16:47:28.693 I/crash_dump64(12463): obtaining output fd from tombstoned
07-18 16:47:28.707 I//system/bin/tombstoned(  618): received crash request for pid 12460
07-18 16:47:28.715 I/crash_dump64(12463): performing dump of process 12460 (target tid = 12460)
07-18 16:47:28.725 F/DEBUG   (12463): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-18 16:47:28.726 F/DEBUG   (12463): Build fingerprint: 'google/bullhead/bullhead:8.0.0/OPP3.170518.006/4055970:user/release-keys'
07-18 16:47:28.726 F/DEBUG   (12463): Revision: 'rev_1.0'
07-18 16:47:28.726 F/DEBUG   (12463): ABI: 'arm64'
07-18 16:47:28.726 F/DEBUG   (12463): pid: 12460, tid: 12460, name: minicap  >>> /data/local/tmp/minicap-devel/minicap <<<
07-18 16:47:28.726 F/DEBUG   (12463): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-18 16:47:28.727 F/DEBUG   (12463): Abort message: 'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap-devel/minicap": library "minicap.so" not found'
07-18 16:47:28.727 F/DEBUG   (12463):     x0   0000000000000000  x1   00000000000030ac  x2   0000000000000006  x3   0000000000000008
07-18 16:47:28.727 F/DEBUG   (12463):     x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000038
07-18 16:47:28.727 F/DEBUG   (12463):     x8   0000000000000083  x9   585b1c62fd5d9264  x10  0000000000000000  x11  0000000000000001
07-18 16:47:28.727 F/DEBUG   (12463):     x12  0000000000000030  x13  0000000000000000  x14  0000000000000000  x15  00243fb08f86234a
07-18 16:47:28.727 F/DEBUG   (12463):     x16  0000007fe53be4cf  x17  0000000000000000  x18  000000006659432b  x19  00000000000030ac
07-18 16:47:28.727 F/DEBUG   (12463):     x20  00000000000030ac  x21  00000055887fda05  x22  0000007fe53bee28  x23  00000055888a1780
07-18 16:47:28.727 F/DEBUG   (12463):     x24  0000006ff82fb280  x25  0000006ff82fc800  x26  0000006ff82fc860  x27  0000007fe53bfe20
07-18 16:47:28.727 F/DEBUG   (12463):     x28  0000006ff82fc000  x29  0000007fe53be9f0  x30  0000006ff82a38d8
07-18 16:47:28.727 F/DEBUG   (12463):     sp   0000007fe53be9b0  pc   0000006ff82b2f7c  pstate 0000000060000000
07-18 16:47:28.735 F/DEBUG   (12463): 
07-18 16:47:28.735 F/DEBUG   (12463): backtrace:
07-18 16:47:28.735 F/DEBUG   (12463):     #00 pc 00000000000a0f7c  /system/bin/linker64 (__dl_tgkill+8)
07-18 16:47:28.735 F/DEBUG   (12463):     #01 pc 00000000000918d4  /system/bin/linker64 (__dl_abort+88)
07-18 16:47:28.735 F/DEBUG   (12463):     #02 pc 0000000000026c2c  /system/bin/linker64 (__dl___libc_fatal+116)
07-18 16:47:28.735 F/DEBUG   (12463):     #03 pc 000000000001b6fc  /system/bin/linker64 (__dl___linker_init+3372)
07-18 16:47:28.735 F/DEBUG   (12463):     #04 pc 0000000000021a44  /system/bin/linker64 (_start+4)
07-18 16:47:28.751 W/NativeCrashListener(  769): Couldn't find ProcessRecord for pid 12460
07-18 16:47:28.751 E/crash_dump64(12463): AM data write failed: Broken pipe
07-18 16:47:28.756 I/BootReceiver(  769): Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
07-18 16:47:29.337 D/BatteryStatsService(  769): begin updateExternalStatsSync reason=battery-level
07-18 16:47:29.362 E/BatteryStatsService(  769): no controller energy info supplied
07-18 16:47:29.372 D/BatteryStatsService(  769): begin getPlatformLowPowerStats
07-18 16:47:29.372 D/BatteryStatsService(  769): end getPlatformLowPowerStats
07-18 16:47:29.377 E/KernelUidCpuFreqTimeReader(  769): Failed to read /proc/uid_time_in_state: java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or directory)
07-18 16:47:29.385 D/BatteryStatsService(  769): end updateExternalStatsSync
07-18 16:47:29.389 E/KernelUidCpuFreqTimeReader(  769): Failed to read /proc/uid_time_in_state: java.io.FileNotFoundException: /proc/uid_time_in_state (No such file or directory)
07-18 16:47:59.266 W/NetRec  (11451): [724] gqk.a: Could not send request to get scores.
